### ISSUE TITLE
Repair healthcheck

### ISSUE THREAD

**Issue by bolet** [erseco/alpine-php-webserver#20]
As configured, php-fpm does not listen on tcp:9000 port.
A possible fix is to use `unix:/run/php-fpm.sock;` in `nginx.conf` fpm-ping block.
I override that file with my own in my docker-compose setup, so I didn't make a PR for the fix.

**Comment by 1ubuntuuser** [comment]
Thank you! I was working on this for the last hour or so.

**Comment by erseco** [comment]
Sorry for the delay on fixing this, I added the fix :)
