### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by amirhosseinchoghaei** [erseco/alpine-php-webserver#25]
hi there ...

i can't write anything with php becuse permission denied ! 

help please

**Comment by erseco** [comment]
Hi @amirhosseinchoghaei ,

The files are under the user `nobody`, which is a non-privileged user to enhance security. 

Please adjust the permissions accordingly to allow PHP to write to the necessary directories. If you need further assistance, feel free to ask.

Best regards,
Ernesto

**Comment by amirhosseinchoghaei** [comment]
i solved this problem with " chown "

thank you so much ...
